---

sys_open_ports: "{{ sys_open_ports_spm }} + {{ sys_open_ports_apigateway }} + {{ sys_open_ports_terracotta }}"

limits_openfiles: "250000"
limits_processes: "20000"

sysctl_config:
  vm.max_map_count: "262144"
  fs.file-max: "{{ limits_openfiles }}"
      
limits_configs:
  - domain: "{{ webmethods_user }}"
    type: soft
    item: nofile
    value: "{{ limits_openfiles }}"
    comment: 'increase the max file descriptor'
  - domain: "{{ webmethods_user }}"
    type: hard
    item: nofile
    value: "{{ limits_openfiles }}"
    comment: 'increase the max file descriptor'
  - domain: "{{ webmethods_user }}"
    type: soft
    item: nproc
    value: "{{ limits_processes }}"
    comment: 'increase the max process limit'
  - domain: "{{ webmethods_user }}"
    type: hard
    item: nproc
    value: "{{ limits_processes }}"
    comment: 'increase the max process limit'

##ensures the SPM service has the right limits applied
webmethods_spm_service_env:
  LimitNOFILE: "{{ limits_openfiles }}"
  LimitNPROC: "{{ limits_processes }}"