---

## OS settings
sys_open_ports: "{{ sys_open_ports_spm }}"
limits_user: "{{ webmethods_user }}"

## some default sysprep values -- will be overriden by other groups
limits_openfiles: "32000"
limits_processes: "5000"

sysctl_config:
  fs.file-max: "{{ limits_openfiles }}"
  
limits_configs:
  - domain: "{{ limits_user }}"
    type: soft
    item: nofile
    value: "{{ limits_openfiles }}"
    comment: 'the max file descriptor'
  - domain: "{{ limits_user }}"
    type: hard
    item: nofile
    value: "{{ limits_openfiles }}"
    comment: 'the max file descriptor'
  - domain: "{{ limits_user }}"
    type: soft
    item: nproc
    value: "{{ limits_processes }}"
    comment: 'the max process limit'
  - domain: "{{ limits_user }}"
    type: hard
    item: nproc
    value: "{{ limits_processes }}"
    comment: 'the max process limit'

## default provisonning values
cce_provisioning_inventory_hosts_pattern: "notspecified"
cce_provisioning_template: "notspecified"
cce_provisioning_properties: "notspecified"
cce_provisioning_template_params: {}
cce_provisioning_template_params_secure: {}
cce_provisioning_inventory_hosts_property: "ansible_host"
cce_provisioning_installed_product_names: "notspecified"
cce_provisioning_installed_product_instance_names: "notspecified"
cce_provisioning_installed_product_envs_by_name:
  LimitNOFILE: "{{ limits_openfiles }}"
  LimitNPROC: "{{ limits_processes }}"
cce_provisioning_postinstall_webmethods: true
cce_provisioning_postinstall_service_setup: true
cce_provisioning_postinstall_reboot: false
cce_provisioning_validation_ports: []
cce_provisioning_validation_ports_timeout: 900