---

# The variables file used by the playbooks in the all_linux group.

sys_open_ports: "{{ sys_open_ports_spm }} + {{ sys_open_ports_internaldatastore }}"

limits_openfiles: "250000"
limits_processes: "20000"

sysctl_config:
  vm.max_map_count: "262144"
  fs.file-max: "{{ limits_openfiles }}"
      
limits_configs:
  - domain: "{{ webmethods_user }}"
    type: soft
    item: nofile
    value: "{{ limits_openfiles }}"
    comment: 'increase the max file descriptor'
  - domain: "{{ webmethods_user }}"
    type: hard
    item: nofile
    value: "{{ limits_openfiles }}"
    comment: 'increase the max file descriptor'
  - domain: "{{ webmethods_user }}"
    type: soft
    item: nproc
    value: "{{ limits_processes }}"
    comment: 'increase the max process limit'
  - domain: "{{ webmethods_user }}"
    type: hard
    item: nproc
    value: "{{ limits_processes }}"
    comment: 'increase the max process limit'

cce_provisioning_stack_product_envs_by_name:
  spm:
    LimitNOFILE: "{{ limits_openfiles }}"
    LimitNPROC: "{{ limits_processes }}"
  internaldatastore:
    LimitNOFILE: "{{ limits_openfiles }}"
    LimitNPROC: "{{ limits_processes }}"
    LimitAS: "infinity"
    LimitFSIZE: "infinity"
    LimitMEMLOCK: "infinity"

webmethods_spm_service_env:
  LimitNOFILE: "{{ limits_openfiles }}"
  LimitNPROC: "{{ limits_processes }}"
