---

## OS settings
sys_open_ports: "{{ sys_open_ports_spm }} + {{ sys_open_ports_cee }}" 

## extra package to install on this type of server profile
extra_packages: ["ant","telnet","wget","bind-utils"]

limits_user: "{{ webmethods_user }}"
limits_openfiles: "250000"
limits_processes: "20000"

## CCE settings
cce_owner: "{{ webmethods_user }}"
cce_group: "{{ webmethods_group }}"

cce_install_dir: "{{ webmethods_install_dir }}"

## cce_provisioning path on final target CCE server
cce_provisioning_code_path: "{{ webmethods_install_dir }}/webmethods-devops-sagcce"

##NOTE: sag content can get big with the images etc... so good idea to make sure the path is a mount point to the larger disk
cce_provisioning_content_path: "{{ webmethods_install_dir }}/webmethods-devops-sagcontent"
cce_provisioning_licenses_path: "{{ cce_provisioning_content_path }}/licenses"
cce_provisioning_images_path: "{{ cce_provisioning_content_path }}/images"
cce_provisioning_installers_path: "{{ cce_provisioning_content_path }}/installers"