---

- hosts: localhost
  become: true
  tasks:
    - name: Non Root tasks
      block:
        ## this is to make sure we gather the facts again as the user {{ cce_owner }} in order to get a valid {{ ansible_env.HOME }}
        - setup:
        - import_role: 
            name: create-known-hosts
      become: false
  tags:
    - sysprep
    - setup_ansible

- hosts: "{{ inventory_groupnames }}"
  become: true
  tasks:
    - import_role: 
        name: manage-packages
    - import_role: 
        name: update-firewall
    - import_role: 
        name: update-os
      vars:
        allow_reboot: false
        sysctl_config:
          net.ipv6.conf.all.disable_ipv6: "1"
          net.ipv6.conf.default.disable_ipv6: "1"
    - import_role: 
        name: update-os

  tags:
    - sysprep
    - sysprep_linux