---

- hosts: localhost
  become: true
  tasks:
    - name: Temp?? Copy automation key from automation user to centos fro easy ansible running
      copy:
        src: /opt/sagenvlnxuser/.ssh/id_rsa
        dest: /home/centos/.ssh/
        owner: centos
        group: centos
        mode: '0600'
        remote_src: yes
    
    - name: Non Root tasks
      block:
        ## this is to make sure we gather the facts again as the user {{ cce_owner }} in order to get a valid {{ ansible_env.HOME }}
        - setup:
        - import_role: 
            name: create-known-hosts
      become: false
  tags:
    - sysprep
    - setup_ansible

- hosts: "{{ inventory_groupnames }}"
  become: true
  roles:
    - role: base-packages
    - role: update-packages
    - role: server-hardening
    
  tags:
    - sysprep
    - sysprep_linux