---

- name: Load vars
  hosts: "*"
  tasks:
    - name: Include vars
      include_vars:
        file: "./vars/base_sysprep.yaml"
  tags:
    - always

## create the wM user with the right SSH key on command central
- hosts: "{{ cce_provisioning_command_central_hosts | default('commandcentral') }}"
  become: true
  tasks:
    - import_role: 
        name: create-service-user
      vars:
        username: "{{ webmethods_user }}"
        userid: "{{ webmethods_userid }}"
        groupname: "{{ webmethods_group }}"
        groupid: "{{ webmethods_groupid }}"
        generate_ssh_key: yes
    - name: Print user output
      debug: var=created_user
    - name: write public key to local file                                                                                
      copy:                                                                                              
        content: "{{ created_user.ssh_public_key }}" 
        dest: "/tmp/created_user_ssh_public_key_{{inventory_hostname}}"
      delegate_to: localhost
  tags:
    - sysprep
    - sysprep_webmethods

## then create the wM user on all the webmethods server using the public key of the key created above
- hosts: "{{ inventory_groupnames }}"
  become: true
  roles:
    - role: create-service-user
      vars:
        username: "{{ webmethods_user }}"
        userid: "{{ webmethods_userid }}"
        groupname: "{{ webmethods_group }}"
        groupid: "{{ webmethods_groupid }}"
        authorized_sshkey_path: "/tmp/created_user_ssh_public_key_*"
    - role: prepare-wminstall
  tasks:
    - name: Add command central DNS into /etc/hosts to make sure it can connect back to it using aliases
      lineinfile:
        dest: /etc/hosts
        regexp: '.*{{ item }}$'
        line: "{{ hostvars[item]['ip'] }} {{ hostvars[item]['hostname'] }} {{ hostvars[item]['fqdn'] }} {{ item }}"
        state: present
      when: hostvars[item]['ip'] is defined and hostvars[item]['hostname'] is defined and hostvars[item]['fqdn'] is defined
      with_items:
        - "{{ groups['commandcentral'] }}"
  tags:
    - sysprep
    - sysprep_webmethods

- hosts: localhost
  become: true
  tasks:
    - name: clear the pub ssh keys
      file:
        path: "{{ item }}"
        state: absent
      with_fileglob:
      - "/tmp/created_user_ssh_public_key_*"
  tags:
    - sysprep
    - sysprep_webmethods