---

- import_playbook: sagenv-sysprep-base.yaml
  vars:
    inventory_groupnames: all_webmethods_apigateway,all_webmethods_apigwinternaldatastore,all_webmethods_apiportal

- import_playbook: sagenv-sysprep-webmethods.yaml
  vars:
    inventory_groupnames: all_webmethods_apigateway,all_webmethods_apigwinternaldatastore,all_webmethods_apiportal

- import_playbook: sagenv-sysprep-cce-provisioning.yaml

##that ensures that the nodes have SPM set properly 
- import_playbook: sagenv-stack-webmethods-generic.yaml
  vars:
    cce_provisioning_stack_name: spm
    cce_provisioning_stack_inventory_groupnames: all_webmethods_apigateway,all_webmethods_apigwinternaldatastore,all_webmethods_apiportal
    cce_provisioning_stack_params: {}
    cce_provisioning_stack_product_names: spm
    cce_provisioning_stack_product_envs_by_name: "{{ webmethods_spm_service_env }}"
  tags:
    - install
    - install-spm

- import_playbook: sagenv-stack-webmethods-generic.yaml
  vars:
    cce_provisioning_stack_name: internaldatastore
    cce_provisioning_stack_inventory_groupnames: all_webmethods_apigwinternaldatastore
    cce_provisioning_stack_params: {}
    cce_provisioning_stack_product_names: internaldatastore
    cce_provisioning_stack_product_envs_by_name: {}
  tags:
    - install
    - install-internaldatastore

##some post install items for alastic search
- hosts: all_webmethods_apigwinternaldatastore
  become: true
  roles:
    - role: elasticsearch-update-seeds
      vars:
        elasticsearch_host_aliases: "{{ groups['all_webmethods_apigwinternaldatastore'] }}"
    - role: elasticsearch-cleardata  
  tags:
    - install
    - postinstall-internaldatastore

- import_playbook: sagenv-stack-webmethods-generic.yaml
  vars:
    cce_provisioning_stack_name: terracotta_cluster
    cce_provisioning_stack_inventory_groupnames: all_webmethods_apigateway
    cce_provisioning_stack_params:
      - name: "LICENSE_KEY_ALIAS_TERRACOTTA"
        value: "Terracotta_v4.x_TerraCotta_v4_Clustering_IS_terracotta-license.key"
    cce_provisioning_stack_product_names: terracotta
    cce_provisioning_stack_product_envs_by_name: {}
  tags:
    - install
    - install-terracotta

##construct the TSA_URL based on the known tarracotta group
- hosts: all_webmethods_cce
  become: true
  become_user: "{{ cce_owner }}"
  tasks:
    - name: set initial facts
      set_fact:
        tsa_target_nodes: []
        tsa_target_url: ""
    - name: Build a list of the inventory hosts
      set_fact:
        tsa_target_nodes: "{{ tsa_target_nodes }} + [ '{{ hostvars[item].ansible_host }}:9510' ]"
      with_items: "{{ groups['all_webmethods_apigateway'] }}"
    - name: join list 
      set_fact:
        tsa_target_url: "{{ tsa_target_nodes | join(',') }}"
  tags:
    - install
    - install-apigw

- import_playbook: sagenv-stack-webmethods-generic.yaml
  vars:
    cce_provisioning_stack_name: apigateway_cluster
    cce_provisioning_stack_inventory_groupnames: all_webmethods_apigateway
    cce_provisioning_stack_params:
      - name: "LICENSE_KEY_ALIAS_APIGW"
        # value: "*_YAIAA_10.1_*_*"
        value: "0000489920_YAIAA_10.1_ANY_AIX"
      - name: "LICENSE_KEY_ALIAS_TERRACOTTA"
        # value: "*TerraCotta_v4_Clustering_IS_terracotta-license.key"
        value: "Terracotta_v4.x_TerraCotta_v4_Clustering_IS_terracotta-license.key"
      - name: "TSA_URL"
        value: "{{ tsa_target_url }}"
    cce_provisioning_stack_product_names: integrationserver
    cce_provisioning_stack_product_envs_by_name: {}
  tags:
    - install
    - install-apigw