---

- name: Load vars
  hosts: "*"
  tasks:
    - name: Include vars
      include_vars:
        file: "./vars/base_sysprep.yaml"
  tags:
    - always

- hosts: localhost
  become: true
  tasks:
    - name: Non Root tasks
      block:
        ## this is to make sure we gather the facts again as the user {{ cce_owner }} in order to get a valid {{ ansible_env.HOME }}
        - setup:
        - import_role: 
            name: create-known-hosts
      become: false
  tags:
    - sysprep
    - setup_ansible

- hosts: "{{ inventory_groupnames }}"
  become: true
  tasks:
    - import_role:
        name: manage-packages
    - name: make sure firewalld is started
      service:
        name: firewalld
        state: started
    - import_role:
        name: update-firewall
    - import_role:
        name: update-dnsresolver-options
    - import_role:
        name: setup-dnsmasq
    - import_role:
        name: update-os
      vars:
        allow_reboot: true
  tags:
    - sysprep
    - sysprep_linux

- import_playbook: sagenv-tools-disabletty.yaml