---

- import_playbook: sagenv-sysprep-base.yaml
  vars:
    inventory_groupnames: all_jenkins,all_webmethods_deployer,all_webmethods_isvaltesting,all_webmethods_abe

- import_playbook: sagenv-sysprep-webmethods.yaml
  vars:
    inventory_groupnames: all_webmethods_deployer,all_webmethods_isvaltesting,all_webmethods_abe

- import_playbook: sagenv-sysprep-cce-provisioning.yaml

- hosts: localhost
  tasks:
    - name: Install jenkins role from ansible-galaxy
      command:
        argv:
          - "ansible-galaxy"
          - install
          - geerlingguy.jenkins,3.8.0
  tags:
    - sysprep

- hosts: all_jenkins
  vars:
    jenkins_hostname: jenkins.{{ env_url_domain }}
    jenkins_package_state: present
    jenkins_version: "2.190.2"
  roles:
    - role: geerlingguy.jenkins
      become: yes
  tags:
    - install
    - install-jenkins


# ##that ensures that the nodes have SPM set properly 
# - import_playbook: sagenv-stack-webmethods-generic.yaml
#   vars:
#     cce_provisioning_stack_name: spm
#     cce_provisioning_stack_inventory_groupnames: all_webmethods_apigateway,all_webmethods_apigwinternaldatastore,all_webmethods_apiportal
#     cce_provisioning_stack_params: {}
#     cce_provisioning_stack_product_names: spm
#     cce_provisioning_stack_product_envs_by_name: "{{ webmethods_spm_service_env }}"
#   tags:
#     - install
#     - install-spm

# - import_playbook: sagenv-stack-webmethods-generic.yaml
#   vars:
#     cce_provisioning_stack_name: deployer
#     cce_provisioning_stack_inventory_groupnames: all_webmethods_deployer
#     cce_provisioning_stack_params: {}
#     cce_provisioning_stack_product_names: integrationserver
#     cce_provisioning_stack_product_envs_by_name: {}
#   tags:
#     - install
#     - install-deployer

# - import_playbook: sagenv-stack-webmethods-generic.yaml
#   vars:
#     cce_provisioning_stack_name: is_stateless
#     cce_provisioning_stack_inventory_groupnames: all_webmethods_isvaltesting
#     cce_provisioning_stack_params: {}
#     cce_provisioning_stack_product_names: integrationserver
#     cce_provisioning_stack_product_envs_by_name: {}
#   tags:
#     - install
#     - install-integrationserver

# - import_playbook: sagenv-stack-webmethods-generic.yaml
#   vars:
#     cce_provisioning_stack_name: abe
#     cce_provisioning_stack_inventory_groupnames: all_webmethods_abe
#     cce_provisioning_stack_params: {}
#     cce_provisioning_stack_product_names:
#     cce_provisioning_stack_product_envs_by_name: {}
#   tags:
#     - install
#     - install-abe