---

- import_playbook: sagenv-sysprep-base.yaml
  vars:
    inventory_groupnames: all_webmethods_cce

- import_playbook: sagenv-sysprep-webmethods.yaml
  vars:
    inventory_groupnames: all_webmethods_cce

##that copies the latest provisioning project if needed
- hosts: all_webmethods_cce
  become: true
  roles:
    - role: prepare-cce-provisoning
  tags:
    - sysprep_cce