---

- hosts: all_linux
  become: true
  tasks:
    - import_role: 
        name: update-os
      vars:
        allow_reboot: true
        sysctl_config:
          net.ipv6.conf.all.disable_ipv6: "1"
          net.ipv6.conf.default.disable_ipv6: "1"