---


- import_playbook: sagenv-sysprep-base.yaml
  vars:
    inventory_groupnames: all_webmethods_cce
  tags:
    - sysprep

- import_playbook: sagenv-sysprep-webmethods.yaml
  vars:
    inventory_groupnames: all_webmethods_cce
  tags:
    - sysprep

- import_playbook: sagenv-sysprep-cce-provisioning.yaml
  tags:
    - sysprep

- hosts: all_webmethods_cce
  tasks:
    - name: Root tasks
      block:
        - import_role: 
            name: update-firewall
        - import_role: 
            name: create-known-hosts
          vars:
            ssh_known_hosts_file: /etc/ssh/ssh_known_hosts
      become: true
    - name: Non Root tasks
      block:
        ## this is to make sure we gather the facts again as the user {{ cce_owner }} in order to get a valid {{ ansible_env.HOME }}
        - setup:
        - import_role: 
            name: create-known-hosts
          vars:
            ssh_known_hosts_file: default
        - import_role: 
            name: install-cce
        - import_role: 
            name: configure-cce
          vars:
            config_item: tuning
        - import_role: 
            name: configure-cce
          vars:
            config_item: creds
        - import_role: 
            name: configure-cce
          vars:
            config_item: licenses
        - import_role: 
            name: configure-cce
          vars:
            config_item: repos
        - import_role: 
            name: configure-cce
          vars:
            config_item: update
      become: true
      become_user: "{{ cce_owner }}"
  post_tasks:
    - name: Non Root tasks
      block:
        - import_role: 
            name: post-install-webmethods
          vars:
            do_reboot: true  
        - name: Wait for CCE ports to become open on the host, don't start checking for 10 seconds
          wait_for:
            port: "{{ item }}"
            delay: 10
            timeout: 300
          with_items:
            - 8090
            - 8091
      become: true
  tags:
    - install_cce