---
  
- hosts: all_webmethods_cce
  become: true
  tasks:
   - name: Provisioning SPM
     command: echo "Provisioning SPM on inventory groups {{ inventory_groupnames }}"

- hosts: "{{ inventory_groupnames }}"
  become: true
  roles:
    - role: update-firewall
      var:
        sys_open_ports: "{{ sys_open_ports_spm }}"
  tags:
    - sysprep

##install SPM
- hosts: all_webmethods_cce
  become: true
  become_user: "{{ cce_owner }}"
  pre_tasks:
    - name: set initial facts
      set_fact:
        inventory_groupnames_hosts: []
    - name: Build a list of the inventory hosts
      set_fact:
        inventory_groupnames_hosts: "{{ inventory_groupnames_hosts }} + {{ groups[item] }}"
      with_items: "{{ inventory_groupnames.split(',') }}"
      when: inventory_groupnames is defined
  roles:
    - role: provision-with-cce
      vars:
        install_host_aliases: "{{ inventory_groupnames_hosts }}"
        install_stackname: spm
  tags:
    - install

##stop SPM process before installing and starting the service
- hosts: "{{ inventory_groupnames }}"
  roles:
    - role: post-install-webmethods
      become: true
    - role: command-webmethods
      vars:
        product: "spm"
        command: "stop"
      become: true
      become_user: "{{ webmethods_user }}"
    - role: update-service
      vars:
        service_name: "{{ webmethods_spm_servicename }}"
        service_state: "restarted"
        service_enabled: true
        service_env: "{{ webmethods_spm_service_env }}"
      become: true
  tags:
    - post-install