---

- import_playbook: sagenv-sysprep-base.yaml
  vars:
    inventory_groupnames: all_webmethods_apigateway,all_webmethods_apigwinternaldatastore,all_webmethods_apiportal
  tags:
    - sysprep

- import_playbook: sagenv-sysprep-webmethods.yaml
  vars:
    inventory_groupnames: all_webmethods_apigateway,all_webmethods_apigwinternaldatastore,all_webmethods_apiportal
  tags:
    - sysprep

##that ensures that the nodes have SPM set properly 
- import_playbook: sagenv-spm-setup-parameterized.yaml
  vars:
    inventory_groupnames: all_webmethods_apigateway,all_webmethods_apigwinternaldatastore,all_webmethods_apiportal
  tags:
    - sysprep

##general provisioning for all the components
- hosts: all_webmethods_cce
  become: true
  become_user: "{{ cce_owner }}"
  roles:
    - role: provision-with-cce
      vars:
        install_host_aliases: "{{ groups['all_webmethods_apigwinternaldatastore'] }}"
        install_stackname: internaldatastore
        postinstall_reboot: true
  tags:
    - provision

# # - hosts: all_webmethods_cce
# #   become: true
# #   become_user: "{{ cce_owner }}"
# #   roles:
# #     - role: provision-with-cce
# #       vars:
# #         install_host_aliases: "{{ groups['all_webmethods_apigateway'] }}"
# #         install_stackname: apigateway
# #         postinstall_reboot: true
# #   tags:
# #     - provision

##general post installs for all the components

- hosts: all_webmethods_apigwinternaldatastore
  become: true
  roles:
    - role: service-webmethods
      vars:
        service_exec_filepath: "{{ webmethods_install_dir }}/InternalDataStore/bin/el_initd"
        service_user: "{{ webmethods_user }}"
        service_name: "sagcel"
    - role: update-service
      vars:
        service_name: "sagcel"
        service_env:
          LimitNOFILE: "65536"
          LimitNPROC: "16000"
          LimitAS: "infinity"
          LimitFSIZE: "infinity"
  tags:
    - post-install