---

### Needs:
### - service_name

- name: get service facts
  service_facts:

- name: Format service name to {{ service_name }}.service for service_facts lookup
  set_fact:
    service_name_index: "{{ service_name }}.service"

- name: Update service state
  service: 
    name: "{{ service_name }}"
    state: "restarted"
    enabled: true
  when: ansible_facts.services[service_name_index] is defined