---

- name: Print the params
  debug:
    msg: "Running service command {{ command }} for product {{ product_name }}"

- name: Include tasks
  include_tasks: "product_{{ product_name }}.yaml"
  when: product_name is defined