---

- import_tasks: "command_{{ command }}.yaml"
  vars:
    service_exec_filepath: "{{ webmethods_install_dir }}/profiles/IS_apigateway/bin/sagis{{ webmethods_install_major_version }}"
    service_name: "sagapigw{{ webmethods_install_major_version }}"