---

  - name: Print the target ansible host aliases to the console.
    debug: var=cce_provisioning_target_host_aliases
  
  - name: Clear the all_host facts
    set_fact:
      all_hostaliases: []
      all_hostnames: []

  - name: Build a list of all the hosts based on ansible aliases
    set_fact:
      all_hostaliases: "{{ all_hostaliases }} + [ '{{ item }}' ]"
      all_hostnames: "{{ all_hostnames }} + [ '{{ hostvars[item].ansible_host }}' ]"
    with_items: "{{ cce_provisioning_target_host_aliases }}"
    when: cce_provisioning_target_host_aliases is defined and (cce_provisioning_target_host_aliases|length>0)

  - name: Print the final target host aliases for stack {{ cce_provisioning_install_stackname }}
    debug: var=all_hostaliases
    
  - name: Print the corresponding target hosts for stack {{ cce_provisioning_install_stackname }}
    debug: var=all_hostnames

  - name: Clear the param file for tack {{ cce_provisioning_install_stackname }}
    command: ./scripts/provision_stack_setparams.sh {{ cce_owner }} {{ cce_provisioning_install_stackname }} {{ item.name }} {{ item.value }} {{ item.append }}
    args:
      chdir: "{{ cce_provisioning_path }}"
    with_items:
      - name: "SOME_DUMMY_PARAM"
        value: "SOME_DUMMY_PARAM_VALUE"
        append: "false"

  - name: Setting target aliases for stack {{ cce_provisioning_install_stackname }}
    command: ./scripts/provision_stack_setparams.sh {{ cce_owner }} {{ cce_provisioning_install_stackname }} {{ item.name }} {{ item.value }} {{ item.append }}
    args:
      chdir: "{{ cce_provisioning_path }}"
    with_items:
      - name: "TARGET_ALIASES"
        value: "[{{ all_hostaliases | join(',') }}]"
        append: "true"
    when: all_hostaliases is defined and (all_hostaliases|length>0)

  - name: Setting target hosts for stack {{ cce_provisioning_install_stackname }}
    command: ./scripts/provision_stack_setparams.sh {{ cce_owner }} {{ cce_provisioning_install_stackname }} {{ item.name }} {{ item.value }} {{ item.append }}
    args:
      chdir: "{{ cce_provisioning_path }}"
    with_items:
      - name: "TARGET_HOSTS"
        value: "[{{ all_hostnames | join(',') }}]"
        append: "true"
    when: all_hostnames is defined and (all_hostnames|length>0)

  - name: Setting params for stack {{ cce_provisioning_install_stackname }}
    command: ./scripts/provision_stack_setparams.sh {{ cce_owner }} {{ cce_provisioning_install_stackname }} {{ item.name }} {{ item.value }} true
    args:
      chdir: "{{ cce_provisioning_path }}"
    with_items: "{{ cce_provisioning_install_params }}"
    when: cce_provisioning_install_params is defined

  ## let's match this async timeout with the CCE job timeout set in the tuning template
  ## timeout.job.seconds: 4800
  - name: Run provision stack {{ cce_provisioning_install_stackname }}
    command: ./scripts/provision_stack.sh {{ cce_owner }} {{ cce_provisioning_install_stackname }}
    async: 4800
    poll: 0
    args:
      chdir: "{{ cce_provisioning_path }}"
    register: provision_stack_sleeper

  ## let's match the retries/delay timeouts with the CCE job timeout set in the tuning template
  ## timeout.job.seconds: 4800
  - name: Check status for tasks {{ cce_provisioning_install_stackname }}
    async_status:
      jid: "{{ provision_stack_sleeper.ansible_job_id }}"
    register: job_result
    until: job_result.finished
    retries: 200
    delay: 24

  - name: Print the job_result to the console.
    debug: var=job_result.stdout_lines

  - name: Copy command result to the server
    copy:
      content: "{{ job_result.stdout }}"
      dest: "{{ ansible_env.HOME }}/provision_stack_{{ inventory_hostname }}_{{ cce_provisioning_install_stackname }}.out"