---

  - name: set initial facts
    set_fact:
      ssh_known_hosts_file: "{{ ssh_known_hosts_file_default }}"
    when: ssh_known_hosts_file == "default"

  - name: clear the {{ ssh_known_hosts_file }} first
    file:
      path: "{{ ssh_known_hosts_file }}"
      state: absent

  - name: touch {{ ssh_known_hosts_file }} file first
    file:
      path: "{{ ssh_known_hosts_file }}"
      state: touch

  - name: For each host, scan for its ssh public key
    shell: "ssh-keyscan -t rsa -H {{ hostvars[item].ansible_host }},`dig +short {{ hostvars[item].ansible_host }}` >> {{ ssh_known_hosts_file }}"
    with_items: "{{ ssh_known_hosts }}"
    register: ssh_known_host_results
    ignore_errors: yes

## not sure why but it throws : Host parameter does not match hashed host field in supplied key -- to be investigated?
  # - name: Add/update the public key in the known_hosts file
  #   known_hosts:
  #     name: "{{ item.item }}"
  #     key: "{{ item.stdout }}"
  #     path: 
  #   with_items: "{{ ssh_known_host_results.results }}"