---

  - name: Forcing the re-configuration of config {{ config_item }}
    file:
      path: "{{ status_success_filepath }}"
      state: absent
    when: configure_cce_force

  - name: Check if CCE config was already done for config {{ config_item }}
    stat: 
      path: "{{ status_success_filepath }}"
    register: stat_cceConfigAlreadyDone

  - name: Prepare and configure CCE only if {{ status_success_filepath }} does not exist.
    block:
      - name: copy private key to user home
        copy: 
          src: "{{ item }}"
          dest: "{{ ansible_env.HOME }}/.ssh/id_rsa" 
          mode: 0600
        with_fileglob:
          - "{{ cce_provisioning_internal_sshkey }}"
        when: config_item == "creds"

      - name: Copy secrets file to target
        copy:
          src: "{{ item }}"
          dest: "{{ ansible_env.HOME }}/.setenv_cce_secrets.sh"
          mode: '0600'
          remote_src: no
        with_fileglob:
          - "{{ cce_provisioning_secrets_path }}"
        when: config_item == "creds"

      - name: Copy license file to target
        copy:
          src: "{{ item }}"
          dest: "{{ ansible_env.HOME }}/sag_licenses.zip"
          mode: '0600'
          remote_src: no
        with_fileglob:
          - "{{ cce_provisioning_license_path }}"
        when: config_item == "licenses"

      - name: Run configure command for config item {{ config_item }}
        command: "/bin/bash ./scripts/configure_ccserver.sh {{ cce_owner }} {{ config_item }}"
        async: 1000
        poll: 0
        args:
          chdir: "{{ cce_provisioning_path }}"
          creates: "{{ status_success_filepath }}"
        register: configure_ccserver_sleeper
        
      - name: Check status of configure command for config item {{ config_item }}
        async_status:
          jid: "{{ configure_ccserver_sleeper.ansible_job_id }}"
        register: job_result
        until: job_result.finished
        retries: 100
        delay: 10

      - name: Copy command result to file {{ status_stdout_filepath }}
        copy:
          content: "{{ job_result.stdout }}"
          dest: "{{ status_stdout_filepath }}"
  
      - name: clear the sensitive file post configure
        file:
          path: "{{ ansible_env.HOME }}/.setenv_cce_secrets.sh"
          state: absent
        when: config_item == "creds"

      - name: clear the sensitive file post configure
        file:
          path: "{{ ansible_env.HOME }}/sag_licenses.zip" 
          state: absent
        when: config_item == "licenses"

    when: stat_cceConfigAlreadyDone.stat.exists == false