---

- import_tasks: command_native.yaml
  vars:
    webmethods_script_dir: "{{ webmethods_install_dir }}/profiles/IS_default/bin"
    webmethods_script_start: "./startup.sh"
    webmethods_script_stop: "./shutdown.sh"