---

- name: Install necessary packages (RHEL)
  package: 
    name: '{{ item }}'
    state: latest
  with_items: "{{mandatory_packages}}"

- name: Install extra packages if any (RHEL)
  package: 
    name: '{{ item }}'
    state: latest
  with_items: "{{extra_packages}}"